# Generated by Django 5.1.3 on 2024-12-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=30)),
                ('food_name', models.CharField(max_length=30)),
                ('food_calories', models.CharField(max_length=30)),
            ],
        ),
    ]
