# Generated by Django 5.1.3 on 2024-12-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_time', models.CharField(max_length=30)),
                ('activity_details', models.CharField(max_length=30)),
                ('breed_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_breed')),
            ],
        ),
    ]
