# Generated by Django 5.1.3 on 2024-12-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_activity',
            old_name='breed_name',
            new_name='breed',
        ),
    ]
