# Generated by Django 5.1.3 on 2024-12-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_abnormalactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_traning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traning_name', models.CharField(max_length=30)),
                ('traning_file', models.URLField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_breed')),
            ],
        ),
    ]
