# Generated by Django 5.1.3 on 2024-12-09 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_delete_tbl_foodplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_foodplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quantity', models.CharField(max_length=30)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_breed')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_food')),
            ],
        ),
    ]
