# Generated by Django 5.1.3 on 2024-12-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_foodplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
