# Generated by Django 5.1.3 on 2024-12-12 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_tbl_vetinaryhospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_fromtime', models.TimeField()),
                ('slot_totime', models.TimeField()),
                ('slot_count', models.CharField(max_length=20)),
                ('vetinaryhospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_vetinaryhospital')),
            ],
        ),
    ]
