# Generated by Django 5.1.3 on 2024-12-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_userreg_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userreg',
            name='user_id',
            field=models.TextField(editable=False, primary_key=True, serialize=False),
        ),
    ]
