# Generated by Django 5.1.3 on 2024-12-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_traning'),
        ('Guest', '0005_alter_tbl_userreg_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vetinaryhospital',
            fields=[
                ('vetinaryhospital_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('vetinaryhospital_name', models.CharField(max_length=40)),
                ('vetinaryhospital_email', models.CharField(max_length=40)),
                ('vetinaryhospital_contact', models.CharField(max_length=40)),
                ('vetinaryhospital_address', models.CharField(max_length=40)),
                ('vetinaryhospital_proof', models.URLField()),
                ('vetinaryhospital_password', models.CharField(max_length=40)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
