# Generated by Django 5.1.3 on 2024-12-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_complaint_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_pet',
        ),
    ]
