# Generated by Django 5.1.3 on 2024-12-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_traning'),
        ('User', '0005_alter_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_foodplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_quantity', models.CharField(max_length=30)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_breed')),
            ],
        ),
    ]
