# Generated by Django 5.1.3 on 2024-12-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_foodplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_foodplan',
        ),
    ]
