# Generated by Django 5.1.3 on 2024-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_appoinment',
            name='appoinment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
