# Generated by Django 5.1.3 on 2024-12-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_appoinment_appoinment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_appoinment',
        ),
    ]
