# Generated by Django 5.1.3 on 2024-12-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_appoinment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_appoinment',
        ),
    ]
