# Generated by Django 5.1.3 on 2024-12-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_appoinment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='appoinment_token',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=30)),
                ('gallery_file', models.URLField()),
                ('gallery_date', models.DateField(auto_now_add=True)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_pet')),
            ],
        ),
    ]
